/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import br.com.sistema.controller.Conexao;

/**
 *
 * @author pedro.costa
 */
public class Area_trabalho extends javax.swing.JFrame {
  

    /**
     * Creates new form Area_trabalho
     */
    public Area_trabalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        ImageIcon icon = new ImageIcon (getClass().getResource("/ImgFundo/sapatek.png"));
        Image image = icon.getImage();
        painel_desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Funcionarios = new javax.swing.JMenu();
        cadastro_funcionarios = new javax.swing.JMenuItem();
        consulta_funcionarios = new javax.swing.JMenuItem();
        Menu_Fonecedores = new javax.swing.JMenu();
        cadastro_fornecedor = new javax.swing.JMenuItem();
        consulta_fornecedor = new javax.swing.JMenuItem();
        Menu_Produtos = new javax.swing.JMenu();
        cadastro_produtos = new javax.swing.JMenuItem();
        produtos_consulta = new javax.swing.JMenuItem();
        configuracoes = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout painel_desktopLayout = new javax.swing.GroupLayout(painel_desktop);
        painel_desktop.setLayout(painel_desktopLayout);
        painel_desktopLayout.setHorizontalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        painel_desktopLayout.setVerticalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        Menu_Funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/imagens/funcionarios.png"))); // NOI18N
        Menu_Funcionarios.setText("Funcionarios");
        Menu_Funcionarios.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Menu_Funcionarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cadastro_funcionarios.setText("Cadastro");
        cadastro_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_funcionariosActionPerformed(evt);
            }
        });
        Menu_Funcionarios.add(cadastro_funcionarios);

        consulta_funcionarios.setText("Consulta");
        consulta_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_funcionariosActionPerformed(evt);
            }
        });
        Menu_Funcionarios.add(consulta_funcionarios);

        jMenuBar1.add(Menu_Funcionarios);

        Menu_Fonecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/imagens/Fornecedores.png"))); // NOI18N
        Menu_Fonecedores.setText("Fornecedores");
        Menu_Fonecedores.setAlignmentX(0.7F);
        Menu_Fonecedores.setAlignmentY(0.7F);

        cadastro_fornecedor.setText("Cadastro");
        cadastro_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_fornecedorActionPerformed(evt);
            }
        });
        Menu_Fonecedores.add(cadastro_fornecedor);

        consulta_fornecedor.setText("Consulta");
        consulta_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_fornecedorActionPerformed(evt);
            }
        });
        Menu_Fonecedores.add(consulta_fornecedor);

        jMenuBar1.add(Menu_Fonecedores);

        Menu_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/imagens/produtos.png"))); // NOI18N
        Menu_Produtos.setText("Produtos");
        Menu_Produtos.setAlignmentX(0.4F);
        Menu_Produtos.setAlignmentY(0.4F);

        cadastro_produtos.setText("Cadastro");
        cadastro_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_produtosActionPerformed(evt);
            }
        });
        Menu_Produtos.add(cadastro_produtos);

        produtos_consulta.setText("Consulta");
        produtos_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtos_consultaActionPerformed(evt);
            }
        });
        Menu_Produtos.add(produtos_consulta);

        jMenuBar1.add(Menu_Produtos);

        configuracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/imagens/configuracao.png"))); // NOI18N
        configuracoes.setText("Configuraçoes");
        jMenuBar1.add(configuracoes);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistema/imagens/sair.png"))); // NOI18N
        sair.setText("Sair");
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void cadastro_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_funcionariosActionPerformed
       Formulario_Funcionarios_cadastro F_ca = new Formulario_Funcionarios_cadastro();
       F_ca.setVisible(true);
    }//GEN-LAST:event_cadastro_funcionariosActionPerformed

    private void consulta_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_funcionariosActionPerformed
        Formulario_Funcionarios_consultar F_co = new Formulario_Funcionarios_consultar();
        F_co.setVisible(true);
    }//GEN-LAST:event_consulta_funcionariosActionPerformed

    private void cadastro_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_fornecedorActionPerformed
        Formulario_Fornecedor_cadastro FO_ca = new Formulario_Fornecedor_cadastro();
        FO_ca.setVisible(true);
    }//GEN-LAST:event_cadastro_fornecedorActionPerformed

    private void consulta_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta_fornecedorActionPerformed
        Formulario_Fornecedor_consulta FO_co = new Formulario_Fornecedor_consulta();
        FO_co.setVisible(true);
    }//GEN-LAST:event_consulta_fornecedorActionPerformed

    private void cadastro_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_produtosActionPerformed
        Formulario_Produtos_cadastro P_ca = new Formulario_Produtos_cadastro();
        P_ca.setVisible(true);
        
    }//GEN-LAST:event_cadastro_produtosActionPerformed

    private void produtos_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtos_consultaActionPerformed
       Formulario_Produtos_consulta P_co = new Formulario_Produtos_consulta ();
       P_co.setVisible(true);
    }//GEN-LAST:event_produtos_consultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windous".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Area_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Area_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Area_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Area_trabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Conexao conexao = new Conexao();
                new Area_trabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Fonecedores;
    private javax.swing.JMenu Menu_Funcionarios;
    private javax.swing.JMenu Menu_Produtos;
    private javax.swing.JMenuItem cadastro_fornecedor;
    private javax.swing.JMenuItem cadastro_funcionarios;
    private javax.swing.JMenuItem cadastro_produtos;
    private javax.swing.JMenu configuracoes;
    private javax.swing.JMenuItem consulta_fornecedor;
    private javax.swing.JMenuItem consulta_funcionarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JDesktopPane painel_desktop;
    private javax.swing.JMenuItem produtos_consulta;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables

    
    private static class Formulario_Funcionarios_consulta {

        public Formulario_Funcionarios_consulta() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

}

  


